% python
>>> def f(a, b, c=1, *d): print a, b, c, d
...
>>> f(3)
Traceback (innermost last):
  File "<stdin>", line 1, in ?
  File "<stdin>", line 1, in f
TypeError: not enough arguments
>>> f(3, 4)
3 4 1 ()
>>> f(3, 4, 5)
3 4 5 ()
>>> f(3, 4, 5, 6)
3 4 5 (6,)
>>> f(3, 4, 5, 6, 7, 8)
3 4 5 (6, 7, 8)

